CREATE DATABASE IF NOT EXISTS `project`;
USE `project`;

CREATE TABLE IF NOT EXISTS `Building` (
  buildingID INT AUTO_INCREMENT PRIMARY KEY,
  building_name VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Department` (
  departmentID INT AUTO_INCREMENT PRIMARY KEY,
  department_name VARCHAR(100) NOT NULL,
  buildingID INT NOT NULL,
  CONSTRAINT fk_dept_building FOREIGN KEY (buildingID)
    REFERENCES Building(buildingID) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Admin` (
  adminID INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Instructor` (
  instructorID INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  birth_date DATE NOT NULL,
  departmentID INT NOT NULL,
  CONSTRAINT fk_instr_dept FOREIGN KEY (departmentID)
    REFERENCES Department(departmentID) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT uc_instructor_name UNIQUE (first_name, last_name, email)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Course` (
  courseID INT AUTO_INCREMENT PRIMARY KEY,
  course_name VARCHAR(150) NOT NULL,
  course_number VARCHAR(20) NOT NULL,
  credits INT NOT NULL,
  departmentID INT NOT NULL,
  CONSTRAINT fk_course_dept FOREIGN KEY (departmentID)
    REFERENCES Department(departmentID) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS `CoursePrerequisite` (
  courseID INT NOT NULL,
  prereqCourseID INT NOT NULL,
  PRIMARY KEY (courseID, prereqCourseID),
  CONSTRAINT fk_prereq_course FOREIGN KEY (courseID)
    REFERENCES Course(courseID) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_prereq_prereqcourse FOREIGN KEY (prereqCourseID)
    REFERENCES Course(courseID) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Classroom` (
  classroomID INT AUTO_INCREMENT PRIMARY KEY,
  room_number INT NOT NULL,
  buildingID INT NOT NULL,
  CONSTRAINT fk_classroom_building FOREIGN KEY (buildingID)
    REFERENCES Building(buildingID) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Timeslot` (
  timeslotID INT AUTO_INCREMENT PRIMARY KEY,
  day_of_week VARCHAR(20) NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Section` (
  sectionID INT AUTO_INCREMENT PRIMARY KEY,
  semester VARCHAR(30) NOT NULL,
  year INT NOT NULL,
  courseID INT NOT NULL,
  instructorID INT NOT NULL,
  classroomID INT NOT NULL,
  timeslotID INT NOT NULL,
  capacity INT NOT NULL DEFAULT 30,
  CONSTRAINT fk_section_course FOREIGN KEY (courseID)
    REFERENCES Course(courseID) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_section_instructor FOREIGN KEY (instructorID)
    REFERENCES Instructor(instructorID) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_section_classroom FOREIGN KEY (classroomID)
    REFERENCES Classroom(classroomID) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_section_timeslot FOREIGN KEY (timeslotID)
    REFERENCES Timeslot(timeslotID) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Student` (
  studentID INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  birth_date DATE NOT NULL,
  year INT NOT NULL,
  term VARCHAR(30) NOT NULL,
  standing VARCHAR(30) NOT NULL,
  major VARCHAR(100) NOT NULL
) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS `Enrollment` (
  enrollmentID INT AUTO_INCREMENT PRIMARY KEY,
  studentID INT NOT NULL,
  sectionID INT NOT NULL,
  grade VARCHAR(6) NOT NULL DEFAULT 'TBD',
  status VARCHAR(20) NOT NULL DEFAULT 'enrolled',
  CONSTRAINT fk_enroll_student FOREIGN KEY (studentID)
    REFERENCES Student(studentID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_enroll_section FOREIGN KEY (sectionID)
    REFERENCES Section(sectionID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT uc_student_section UNIQUE (studentID, sectionID)
) ENGINE=InnoDB;
